typography_spectrum: 0.20715153845958412
color:
  brandColors:
    - '#f8f8f8'
    - '#9f3b41'
    - '#25321a'
    - '#a79f90'
    - '#f5c296'
  brandStrength: 0.5
  lightness: 0.6801770213060081
  saturation: 0.9149102126248181
  rhythmicContrast: 0.18901853589341044
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.88003
analytics:
  google: null
  facebook: null
  twitter: null
name: Simpleet
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Company
    url: 'http://simpleet.com'
    type: external
favicon: null
title: Simpleet & The Grid
description: Made with The Grid
purpose: []
