name: Simpleet
favicon: null
layout_spectrum: 0.88003
typography_spectrum: 0.20715153845958412
title: 'Simpleet & The Grid'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f8f8f8'
    - '#9f3b41'
    - '#25321a'
    - '#a79f90'
    - '#f5c296'
  brandStrength: 0.5
  lightness: 0.6801770213060081
  saturation: 0.9149102126248181
  rhythmicContrast: 0.18901853589341044
purpose: []
